[package]
name = "space-car-football"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = "0.10.0"
bevy_rapier_collider_gen = "0.1.2"
bevy_rapier2d = {version = "0.21.0", features = ["simd-stable", "wasm-bindgen"]}
leafwing-input-manager = "0.9.2"